### ISSUE TITLE
html_options multiple selections

### ISSUE THREAD

**Issue by benique** [miroshnikov/jsmart#41]
I think there is a problem with html_options and multiple selected values. I have tried all code variations I could think of but none works. It only selects one value if it selects one at all.

    {html_options values=['1','2','3','4'] output=['one','two','three','four'] selected=['1'']}

Output:

     <option value="1" selected="selected">one</option>
     <option value="2">two</option>
     <option value="3">three</option>
     <option value="4">four</option>

    {html_options values=['1','2','3','4'] output=['one','two','three','four'] selected=['1','3']}

Output:

     <option value="1">one</option>
     <option value="2">two</option>
     <option value="3">three</option>
     <option value="4">four</option>

Expected output:

     <option value="1" selected="selected">one</option>
     <option value="2">two</option>
     <option value="3" selected="selected">three</option>
     <option value="4">four</option>

**Comment by miroshnikov** [comment]
fixed in https://github.com/miroshnikov/jsmart/commit/1787b93e0333f87a7d6a4c3d1c8cd48693044eb3
