### ISSUE TITLE
foreach with objects

### ISSUE THREAD

**Issue by Spec1alFx** [miroshnikov/jsmart#42]
Hi,
I had a problem with a simple foreach:

{foreach $FileList as $Key => $File}
    <img src="/files/{$File['FileID']}" />
{/foreach}

$FileList is an object like this:

[12/c108cc0cde03c332305ecb74be64a476.png: Object]
   12/c108cc0cde03c332305ecb74be64a476.png: Object
      FileID: "12/c108cc0cde03c332305ecb74be64a476.png"

But the foreach doesn't work. I found that the problem is the if statement @ row 680:

if (!(a instanceof Object))

changed to:

if (!(typeof a == 'object'))

and it works fine. I think that the origin of the problem is that I use jsmart inside a iframe and FileList comes from the parent window, and it fails to compare the object of the parent window with the "Object" of the iframe.

I'm opening this issue because I'm not satisfied with a solution that requires to manually patch external libraries. :)

Thank you!

**Comment by miroshnikov** [comment]
https://github.com/miroshnikov/jsmart/commit/1787b93e0333f87a7d6a4c3d1c8cd48693044eb3
