### ISSUE TITLE
empty function

### ISSUE THREAD

**Issue by LRoffic** [miroshnikov/jsmart#43]
Hi, I want to know if it were possible that you add compatibility for the "empty" depending on the conditions
Example:
{if !empty($var)} // {if empty($var)}

**Comment by miroshnikov** [comment]
Do you mean a full analog of the php empty() function as it is described here - http://php.net/manual/en/function.empty.php ?
Well, probably it would be a good idea.

**Comment by LRoffic** [comment]
Yes, I meant this php function.

**Comment by alex-shamshurin** [comment]
There is a PHPJS version of empty 

```
/**
 * PHP Empty
 * @param mixedVar
 * @returns {boolean}
 */
function empty (mixedVar) {
	var undef;
	var key;
	var i;
	var len;
	var emptyValues = [undef, null, false, 0, '', '0'];

	for (i = 0, len = emptyValues.length; i < len; i++) {
		if (mixedVar === emptyValues[i]) {
			return true
		}
	}

	if (typeof mixedVar === 'object') {
		for (key in mixedVar) {
			if (mixedVar.hasOwnProperty(key)) {
				return false
			}
		}
		return true
	}

	return false
}

```

**Comment by LRoffic** [comment]
Thank you :smiley:

**Comment by miroshnikov** [comment]
Actually there is no need for a special function like this. You can use `!` operator whenever you need to check if a variable is 'empty'. It works just the same.
